// methods

//size(),

//clear() : delete all items in the set

//isEmpty() : return true if size is 0

// contains(valueToCheck)

//remove(valueToDelete)

System.debug('numberSet.size()  value is : ' + numberSet.size() );
// clear()   : delete all items in the Set 
numberSet.clear(); 
 System.debug('numberSet value is : ' + numberSet); 
// isEmpty()  : return true if size is 0 , return false if not 
System.debug('numberSet.isEmpty()  value is : ' + numberSet.isEmpty() ); 
