while(muffin >= 0){

    if(muffin > 10){
        System.debug('first half : muffin count is ' + muffin);
        muffin -= 3 ; 
    }else{
        System.debug('second half : muffin count is ' + muffin);
        muffin -= 2 ; 
    }

}

do {

    if(muffin > 10){
        System.debug('first half : muffin count is ' + muffin);
        muffin -= 3 ; 
    }else{
        System.debug('second half : muffin count is ' + muffin);
        muffin -= 2 ; 
    }

}while(muffin >= 0) ; 